### ISSUE TITLE
Error Event events.js:160 on Login

### ISSUE THREAD

**Issue by Glock21x45ACP** [IonicaBizau/cli-github#40]
Upon logging in and auto fetching the news feed, I receive an error and it boots me out of the app. 

events.js:160
      throw er; // Unhandled 'error' event
      ^

TypeError: Cannot read property 'length' of undefined
    at /usr/local/lib/node_modules/cli-github/lib/api/stream.js:51:50
    at Parser.<anonymous> (/usr/local/lib/node_modules/cli-github/node_modules/xml2js/lib/xml2js.js:489:18)
    at emitOne (events.js:96:13)
    at Parser.emit (events.js:188:7)
    at Object.onclosetag (/usr/local/lib/node_modules/cli-github/node_modules/xml2js/lib/xml2js.js:447:26)
    at emit (/usr/local/lib/node_modules/cli-github/node_modules/sax/lib/sax.js:640:35)
    at emitNode (/usr/local/lib/node_modules/cli-github/node_modules/sax/lib/sax.js:645:5)
    at closeTag (/usr/local/lib/node_modules/cli-github/node_modules/sax/lib/sax.js:905:7)
    at Object.write (/usr/local/lib/node_modules/cli-github/node_modules/sax/lib/sax.js:1449:13)
    at Parser.exports.Parser.Parser.parseString (/usr/local/lib/node_modules/cli-github/node_modules/xml2js/lib/xml2js.js:508:31)

**Comment by IonicaBizau** [comment]
Hmm, interesting. Can you tell me what Node.js version you are running?

**Comment by keclarke** [comment]
install : node-v7.4.0
       mkdir : /usr/local/n/versions/node/7.4.0
       fetch : https://nodejs.org/dist/v7.4.0/node-v7.4.0-darwin-x64.tar.gz
######################################################################## 100.0%
   installed : v7.4.0

**Comment by aditya7iyengar** [comment]
I'm getting the same error!

**Comment by IonicaBizau** [comment]
Probably it fails to read the `length`: https://github.com/IonicaBizau/cli-github/blob/master/lib/api/stream.js#L46

**Comment by robcapell** [comment]
After login:
```bash
events.js:183
      throw er; // Unhandled 'error' event
      ^

TypeError: callback is not a function
    at /usr/local/lib/node_modules/cli-github/lib/ui/stream.js:41:14
    at /usr/local/lib/node_modules/cli-github/lib/api/stream.js:48:24
    at Parser.<anonymous> (/usr/local/lib/node_modules/cli-github/node_modules/xml2js/lib/parser.js:307:18)
    at emitOne (events.js:116:13)
    at Parser.emit (events.js:211:7)
    at SAXParser.onerror (/usr/local/lib/node_modules/cli-github/node_modules/xml2js/lib/parser.js:122:26)
    at emit (/usr/local/lib/node_modules/cli-github/node_modules/sax/lib/sax.js:624:35)
    at error (/usr/local/lib/node_modules/cli-github/node_modules/sax/lib/sax.js:653:5)
    at strictFail (/usr/local/lib/node_modules/cli-github/node_modules/sax/lib/sax.js:677:7)
    at beginWhiteSpace (/usr/local/lib/node_modules/cli-github/node_modules/sax/lib/sax.js:951:7)
```

Node Version:
```bash
$ node -v
v8.9.1
```

NPM Version:
```bash
```

**Comment by andyjk15** [comment]
Getting the same issue too. On OSX High Sierra 10.13.3

**Comment by Shinoa-Fores** [comment]
Over a year later and this still isn't fixed ... likely going to mark this as garbage.

**Comment by IonicaBizau** [comment]
Installing [graphicsmagick](https://github.com/IonicaBizau/cli-github#prerequisites) should fix this.
